module.exports = (grunt)->
  version = ->
    grunt.file.readJSON("package.json").version
  version_text = ->
    "v#{version()}"

  repo = "https://github.com/dylan/treap.js"

  grunt.initConfig
    pkg: grunt.file.readJSON("package.json")
    repo: "https://github.com/dylan/treap.js"

    comments: """
//
// <%= pkg.name %>
// v<%= pkg.version %>
// Built on <%= grunt.template.today("yyyy-mm-dd") %>
// Full source at <%= repo %>
//
// MIT License, <%= repo %>/blob/master/LICENSE
// This file is generated by `grunt build` do not edit it by hand.
//\n\n
"""
    minified_comments: "/* <%= pkg.name %> v<%= pkg.version %>, MIT License <%= repo %>/blob/master/LICENSE */\n"

    coffee:
      compile:
        options:
          bare: true
          sourceMap: true
        files:
          'lib/treap.js': 'coffee/**/*.coffee'
          'spec/treap.js': 'spec/*.coffee'
          'benchmarks/all.js':'benchmarks/all.coffee'

    jasmine :
      src : 'lib/**/*.js',
      options :
        specs : 'spec/**/*.js'

    uglify:
      options:
        mangle:
          except: ['node', 'treap']
        banner: "<%= minified_comments %>"

      minify:
        files:
          'lib/treap.min.js': ['lib/treap.js']

    coffeelint:
      source: 'coffee/**/*.coffee'

    clean:
      dist: ['lib/*.js','lib/*.map']

    watch:
      scripts:
        files: ['coffee/**/*.coffee','spec/*.coffee','benchmarks/*.coffee']
        tasks: ['build','test']

    concat:
      bench:
        src: ['lib/treap.js','benchmarks/all.js']
        dest: 'benchmarks/all.js'

    benchmark:
      all:
        src:'benchmarks/all.js'
        dest:'benchmarks/results.csv'

  grunt.loadNpmTasks 'grunt-contrib-watch'
  grunt.loadNpmTasks 'grunt-contrib-clean'
  grunt.loadNpmTasks 'grunt-contrib-coffee'
  grunt.loadNpmTasks 'grunt-contrib-uglify'
  grunt.loadNpmTasks 'grunt-notify'
  grunt.loadNpmTasks 'grunt-coffeelint'
  grunt.loadNpmTasks 'grunt-contrib-jasmine'
  grunt.loadNpmTasks 'grunt-contrib-concat'
  grunt.loadNpmTasks 'grunt-benchmark'

  grunt.registerTask 'default', ['build']
  grunt.registerTask 'lint',    ['coffeelint']
  grunt.registerTask 'test',    ['jasmine','concat','benchmark']
  grunt.registerTask 'build',   ['coffeelint','coffee','uglify']
